[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "https://marinelaserclean.com/*"
  to = "https://www.marinelaserclean.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
