import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'es' | 'en' | 'zh';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  es: {
    // Navigation
    'nav.home': 'Inicio',
    'nav.about': 'Nosotros',
    'nav.services': 'Servicios',
    'nav.gallery': 'Galería',
    'nav.contact': 'Contacto',
    
    // Home
    'home.hero.title': 'Limpieza Láser Industrial',
    'home.hero.subtitle': 'Máquina láser de 6000W para preparación de superficies, remoción de óxido y limpieza industrial de alta potencia',
    'home.hero.cta': 'Solicitar Cotización',
    'home.hero.cta2': 'Ver Servicios',
    'home.features.title': '¿Por Qué Elegirnos?',
    'home.features.precision.title': 'Cero Daño al Sustrato',
    'home.features.precision.desc': 'Tecnología láser que elimina solo la contaminación, preservando el metal base sin abrasión',
    'home.features.eco.title': 'Sin Residuos Secundarios',
    'home.features.eco.desc': 'Sin medios abrasivos, químicos ni costos de disposición. Solo polvo mínimo capturado',
    'home.features.efficient.title': 'Dramáticamente Más Rápido',
    'home.features.efficient.desc': 'Limpia áreas grandes rápidamente, reduciendo tiempo de inactividad del cliente',
    'home.features.versatile.title': 'Precisión Láser',
    'home.features.versatile.desc': 'Limpia áreas específicas como soldaduras sin afectar el material circundante',
    'home.power.title': 'Potencia Industrial de 6000W',
    'home.power.desc': 'Equipo de alta potencia para aplicaciones industriales pesadas y proyectos de gran escala',
    
    // About
    'about.title': 'Sobre Nosotros',
    'about.subtitle': 'Proveedores especializados de servicios de limpieza láser industrial',
    'about.intro': 'Operamos un sistema láser de limpieza de óxido de 6000W de alta potencia, ofreciendo servicios de preparación de superficies de nivel industrial para manufactura pesada, marítima, energía y sectores aeroespaciales. Nuestro equipo de Clase 4 maneja proyectos de gran escala donde el tiempo de inactividad del cliente es crítico.',
    'about.mission.title': 'Nuestra Tecnología',
    'about.mission.desc': 'Sistema láser de 6000W para aplicaciones industriales pesadas. Limpieza rápida de grandes áreas con cero daño al sustrato, sin medios abrasivos y sin residuos químicos. Operación remota para entornos peligrosos.',
    'about.vision.title': 'Modelo de Negocio',
    'about.vision.desc': 'Proveedor de servicios B2B ofreciendo contratos móviles, por proyecto y de mantenimiento. Nos especializamos en educación del mercado sobre las ventajas económicas y ambientales sobre métodos tradicionales.',
    'about.values.title': 'Ventajas Clave',
    'about.values.quality': 'Sin Desperdicio',
    'about.values.innovation': 'Más Rápido',
    'about.values.commitment': 'Seguro',
    'about.values.safety': 'Preciso',
    
    // Services
    'services.title': 'Servicios Industriales de Limpieza Láser',
    'services.subtitle': 'Soluciones B2B para manufactura pesada, marítima, energía y más',
    'services.ship.title': 'Marítimo & Construcción Naval',
    'services.ship.desc': 'Remoción de óxido, percebes y pintura vieja de cascos de barcos en dique seco. Limpieza de tanques de lastre y bodegas de carga. Más rápido y limpio que el arenado tradicional.',
    'services.machinery.title': 'Manufactura & Fabricación',
    'services.machinery.desc': 'Pre-tratamiento para soldadura de placas de acero, vigas y tuberías. Preparación de superficies para pintura en turbinas eólicas, cascos de barcos y tanques de almacenamiento. Mantenimiento de moldes sin daño abrasivo.',
    'services.rust.title': 'Energía & Infraestructura',
    'services.rust.desc': 'Limpieza de calderas, intercambiadores de calor y tuberías en plantas de energía. Mantenimiento de torres eólicas. Restauración de puentes sin contención de polvo tóxico de pintura con plomo.',
    'services.parts.title': 'Aeroespacial & Automotriz',
    'services.parts.desc': 'Refabricación de álabes de turbina y componentes de motor donde la precisión es primordial. Restauración de chasis de autos clásicos y bloques de motor. Cero daño al sustrato.',
    'services.coating.title': 'Recubrimiento de Pintura',
    'services.coating.desc': 'Servicios completos de recubrimiento de pintura complementarios a la limpieza láser. Aplicación profesional de pinturas industriales, anticorrosivas y epóxicas para máxima protección después de la preparación láser.',
    
    // Gallery
    'gallery.title': 'Galería de Trabajos',
    'gallery.subtitle': 'Vea la calidad de nuestro trabajo',
    'gallery.before': 'Antes',
    'gallery.after': 'Después',
    
    // Contact
    'contact.title': 'Contáctenos',
    'contact.subtitle': 'Estamos aquí para ayudarle',
    'contact.name': 'Nombre',
    'contact.email': 'Correo Electrónico',
    'contact.phone': 'Teléfono',
    'contact.message': 'Mensaje',
    'contact.send': 'Enviar Mensaje',
    'contact.info.title': 'Información de Contacto',
    'contact.info.location': 'Cabimas, Zulia, Venezuela',
    'contact.info.phone': '0412-324-3681',
    'contact.info.email': 'lasercleanvz@proton.me',
    
    // Footer
    'footer.rights': 'Todos los derechos reservados',
    'footer.location': 'Cabimas, Zulia, Venezuela',
    'footer.company': 'Marine Laser Clean',
    'footer.privacy': 'Política de Privacidad',
    'footer.cookies': 'Política de Cookies',
    
    // SEO Meta Tags
    'seo.home.title': 'Marine Laser Clean | Limpieza Láser Industrial 6000W en Venezuela',
    'seo.home.description': 'Servicios profesionales de limpieza láser industrial con equipo de 6000W. Remoción de óxido, preparación de superficies para soldadura, limpieza marítima y más. Cabimas, Zulia, Venezuela.',
    'seo.about.title': 'Sobre Nosotros | Marine Laser Clean - Expertos en Limpieza Láser',
    'seo.about.description': 'Conozca nuestra tecnología de limpieza láser de 6000W. Proveedores especializados de servicios B2B para industria marítima, manufactura, energía y aeroespacial.',
    'seo.services.title': 'Servicios de Limpieza Láser Industrial | Marine Laser Clean',
    'seo.services.description': 'Servicios de limpieza láser para marítimo, manufactura, energía e infraestructura. Remoción de óxido, preparación de soldadura, mantenimiento de equipos sin daño al sustrato.',
    'seo.gallery.title': 'Galería de Trabajos | Marine Laser Clean - Antes y Después',
    'seo.gallery.description': 'Vea resultados reales de limpieza láser industrial. Fotos antes y después de cascos de barcos, maquinaria, tuberías y componentes industriales.',
    'seo.contact.title': 'Contáctenos | Marine Laser Clean - Solicite Cotización',
    'seo.contact.description': 'Solicite una cotización para servicios de limpieza láser industrial. Ubicados en Cabimas, Zulia, Venezuela. Atención personalizada para su proyecto.',
    
    // Blog
    'nav.blog': 'Blog',
    'blog.title': 'Blog de Limpieza Láser Industrial',
    'blog.subtitle': 'Noticias, consejos y conocimientos sobre tecnología de limpieza láser',
    'blog.metaTitle': 'Blog de Limpieza Láser Industrial | Marine Laser Clean',
    'blog.metaDescription': 'Aprenda sobre limpieza láser industrial, remoción de óxido, preparación de superficies y alternativas ecológicas al sandblasting para industrias marítimas y de manufactura.',
    'blog.readMore': 'Leer más',
    'blog.category.comparison': 'Comparación',
    'blog.category.maritime': 'Marítimo',
    'blog.category.industry': 'Industria',
    'blog.category.environment': 'Medio Ambiente',
    'blog.category.energy': 'Energía',
    'blog.category.aerospace': 'Aeroespacial',
    'blog.category.technique': 'Técnica',
    'blog.category.oilgas': 'Petróleo y Gas',
    'blog.category.welding': 'Soldadura',
    'blog.category.restoration': 'Restauración',
    'blog.post1.title': 'Limpieza Láser vs Sandblasting: Comparación Completa para Industria',
    'blog.post1.excerpt': 'Descubra por qué la limpieza láser está reemplazando al sandblasting tradicional en aplicaciones marítimas e industriales. Comparamos costo, velocidad, impacto ambiental y resultados.',
    'blog.post2.title': 'Guía Completa de Remoción de Óxido en Cascos de Barcos',
    'blog.post2.excerpt': 'Aprenda las mejores prácticas para el mantenimiento de cascos de barcos usando tecnología láser. Incluye antes/después, estimaciones de tiempo y beneficios de costos.',
    'blog.post3.title': '5 Beneficios de la Limpieza Láser Industrial en Manufactura',
    'blog.post3.excerpt': 'Cómo los fabricantes ahorran tiempo y dinero con limpieza láser para preparación de soldadura, mantenimiento de moldes y restauración de superficies.',
    'blog.post4.title': 'Preparación de Superficies Ecológica: El Futuro de la Limpieza Industrial',
    'blog.post4.excerpt': 'Explore cómo la limpieza láser elimina residuos peligrosos y cumple con regulaciones ambientales mientras ofrece resultados superiores.',
    'blog.post5.title': 'Mantenimiento de Turbinas Eólicas con Tecnología Láser',
    'blog.post5.excerpt': 'Estudio de caso: Cómo la limpieza láser reduce el tiempo de inactividad y extiende la vida útil de componentes de turbinas eólicas.',
    'blog.post6.title': 'Limpieza de Precisión para Componentes Aeroespaciales',
    'blog.post6.excerpt': 'Por qué las industrias aeroespacial y automotriz eligen la limpieza láser para restauración de álabes de turbina y bloques de motor.',
    'blog.cta.title': '¿Listo para Transformar su Proceso de Limpieza?',
    'blog.cta.description': 'Contáctenos para una consulta gratuita y descubra cómo la limpieza láser puede beneficiar su operación.',
    'blog.cta.button': 'Solicitar Cotización',
    'blog.backToBlog': 'Volver al Blog',
    'blog.readTime': 'de lectura',
    'blog.share': 'Compartir',
    'blog.relatedPosts': 'Artículos Relacionados',
    'blog.post1.content': '<h2>¿Qué es la Limpieza Láser?</h2><p>La limpieza láser utiliza pulsos de luz de alta energía para vaporizar contaminantes como óxido, pintura y aceite de las superficies metálicas. A diferencia del sandblasting, no hay medios abrasivos que dañen el sustrato base.</p><h2>Comparación de Costos</h2><p>Aunque el equipo láser tiene un costo inicial más alto, los ahorros a largo plazo son significativos: sin consumibles, sin costos de eliminación de residuos peligrosos, y menor mantenimiento del equipo.</p><h2>Velocidad de Trabajo</h2><p>Con sistemas de 6000W como el nuestro, la limpieza láser puede ser hasta 10 veces más rápida que los métodos tradicionales en ciertas aplicaciones, reduciendo dramáticamente el tiempo de inactividad.</p><h2>Impacto Ambiental</h2><p>El sandblasting genera toneladas de residuos contaminados. La limpieza láser produce solo polvo mínimo que se captura fácilmente, cumpliendo con las regulaciones ambientales más estrictas.</p><h2>Resultados y Calidad</h2><p>La limpieza láser ofrece resultados consistentes y repetibles, con control preciso sobre la profundidad de limpieza, algo imposible de lograr con sandblasting.</p>',
    'blog.post2.content': '<h2>Desafíos del Mantenimiento de Cascos</h2><p>Los cascos de barcos enfrentan corrosión constante por agua salada, incrustaciones marinas y degradación de pintura. El mantenimiento regular es esencial para la eficiencia del combustible y la integridad estructural.</p><h2>Proceso de Limpieza Láser</h2><p>Nuestro sistema de 6000W elimina eficientemente capas de óxido, percebes y pintura vieja sin dañar el acero subyacente. El proceso es seco, limpio y no genera residuos secundarios.</p><h2>Ventajas en Dique Seco</h2><p>El tiempo en dique seco es costoso. La limpieza láser reduce significativamente el tiempo de preparación de superficie, permitiendo que los barcos vuelvan al servicio más rápido.</p><h2>Preparación para Pintura</h2><p>La superficie resultante es ideal para la adhesión de nuevos recubrimientos, con un perfil de anclaje óptimo creado por el proceso láser.</p><h2>Casos de Éxito</h2><p>Hemos tratado exitosamente cascos de hasta 200 metros de longitud, con resultados consistentes y clientes satisfechos en toda la industria marítima.</p>',
    'blog.post3.content': '<h2>Reducción de Tiempo de Inactividad</h2><p>En manufactura, cada hora de parada cuesta dinero. La limpieza láser puede realizarse durante mantenimientos programados cortos, minimizando interrupciones en la producción.</p><h2>Preparación de Soldadura Superior</h2><p>Una superficie perfectamente limpia es crucial para soldaduras de calidad. El láser elimina óxidos, aceites y contaminantes sin dejar residuos que afecten la soldadura.</p><h2>Mantenimiento de Moldes</h2><p>Los moldes de inyección requieren limpieza regular. La limpieza láser no causa desgaste como los métodos abrasivos, extendiendo la vida útil del molde significativamente.</p><h2>Ahorro en Consumibles</h2><p>Sin arena, sin químicos, sin materiales desechables. Los únicos costos operativos son electricidad y mantenimiento mínimo del equipo.</p><h2>ROI Comprobado</h2><p>Nuestros clientes reportan recuperación de inversión en menos de 18 meses gracias a la eliminación de consumibles y reducción de tiempo de proceso.</p>',
    'blog.post4.content': '<h2>Regulaciones Ambientales</h2><p>Las normativas cada vez más estrictas hacen que los métodos tradicionales como el sandblasting sean costosos de cumplir. La limpieza láser simplifica el cumplimiento regulatorio.</p><h2>Cero Residuos Peligrosos</h2><p>El sandblasting con pintura de plomo genera residuos tóxicos costosos de eliminar. La limpieza láser vaporiza los contaminantes, dejando solo ceniza fácil de contener.</p><h2>Salud del Trabajador</h2><p>Sin polvo abrasivo en el aire significa un ambiente de trabajo más seguro. Los operadores solo necesitan protección ocular básica contra el láser.</p><h2>Huella de Carbono</h2><p>Menor consumo de energía total comparado con compresores de aire para sandblasting, y sin emisiones de transporte de medios abrasivos.</p><h2>El Futuro es Láser</h2><p>Las principales industrias ya están migrando a tecnología láser. Adoptar ahora significa estar preparado para futuras regulaciones.</p>',
    'blog.post5.content': '<h2>Desafíos Únicos de Turbinas Eólicas</h2><p>Las turbinas eólicas operan en ambientes hostiles: sal marina, arena, lluvia ácida. El mantenimiento regular es crucial pero difícil debido a su altura y ubicación.</p><h2>Limpieza de Palas</h2><p>Las palas acumulan suciedad y erosión que reducen la eficiencia aerodinámica. La limpieza láser restaura la superficie sin dañar el material compuesto.</p><h2>Torres y Nacelas</h2><p>El acero de las torres sufre corrosión. Nuestros sistemas portátiles pueden desplegarse en campo para mantenimiento in-situ.</p><h2>Reducción de Costos de Mantenimiento</h2><p>Comparado con andamios y sandblasting a altura, la limpieza láser con sistemas móviles reduce significativamente los costos y riesgos.</p><h2>Extensión de Vida Útil</h2><p>El mantenimiento preventivo regular con láser puede extender la vida útil de componentes críticos en años, mejorando el retorno de inversión de parques eólicos.</p>',
    'blog.post6.content': '<h2>Estándares Aeroespaciales</h2><p>La industria aeroespacial tiene los estándares de calidad más exigentes. La limpieza láser cumple y supera estos requisitos sin comprometer la integridad del material.</p><h2>Refabricación de Álabes de Turbina</h2><p>Los álabes de turbina de aviación son extremadamente costosos. La limpieza láser permite refabricarlos múltiples veces sin degradación del sustrato.</p><h2>Componentes de Motor</h2><p>Pistones, culatas y bloques de motor requieren limpieza precisa. El láser elimina depósitos de carbono sin afectar tolerancias críticas.</p><h2>Restauración Automotriz</h2><p>Vehículos clásicos y de colección se benefician de limpieza láser que revela el metal original sin daño, preservando el valor histórico.</p><h2>Trazabilidad y Documentación</h2><p>Nuestros sistemas pueden documentar cada proceso para cumplir con requisitos de trazabilidad aeroespacial y automotriz.</p>',
    'blog.post7.title': 'Guía Completa de Remoción de Pintura con Tecnología Láser',
    'blog.post7.excerpt': 'Aprenda cómo la tecnología láser revoluciona la remoción de pintura industrial, ofreciendo resultados superiores sin dañar el sustrato base.',
    'blog.post7.content': '<h2>Remoción de Pintura Tradicional vs Láser</h2><p>Los métodos tradicionales como el decapado químico y el sandblasting tienen limitaciones significativas. Los químicos son tóxicos y el sandblasting daña el sustrato. La limpieza láser elimina estas preocupaciones.</p><h2>Cómo Funciona</h2><p>El láser calienta rápidamente la capa de pintura, vaporizándola instantáneamente. El sustrato metálico absorbe menos energía, permaneciendo intacto y listo para nuevo recubrimiento.</p><h2>Tipos de Pintura</h2><p>Nuestro sistema de 6000W maneja todo tipo de pinturas: epóxicas, poliuretánicas, anticorrosivas, e incluso pinturas con plomo de forma segura.</p><h2>Aplicaciones Industriales</h2><p>Ideal para renovación de flotas de vehículos, mantenimiento de equipos industriales, preparación de estructuras metálicas y restauración de maquinaria.</p><h2>Ventajas Económicas</h2><p>Sin costos de disposición de residuos químicos, menor tiempo de trabajo, y superficie lista para repintar inmediatamente.</p>',
    'blog.post8.title': 'Limpieza Láser en la Industria del Petróleo y Gas',
    'blog.post8.excerpt': 'Descubra cómo la limpieza láser está transformando el mantenimiento de equipos en la industria petrolera con soluciones más seguras y eficientes.',
    'blog.post8.content': '<h2>Desafíos de la Industria Petrolera</h2><p>Los equipos petroleros enfrentan condiciones extremas: corrosión por H2S, incrustaciones de hidrocarburos, y ambientes explosivos. La limpieza tradicional presenta riesgos significativos.</p><h2>Seguridad en Zonas ATEX</h2><p>Nuestros equipos láser pueden configurarse para operación segura en áreas clasificadas, eliminando riesgos de chispas asociados con métodos abrasivos.</p><h2>Limpieza de Tuberías y Válvulas</h2><p>La precisión del láser permite limpiar superficies internas de tuberías y componentes de válvulas sin desmontaje extensivo.</p><h2>Mantenimiento de Plataformas</h2><p>Las estructuras offshore requieren mantenimiento constante contra la corrosión marina. La limpieza láser portátil reduce tiempos de parada operacional.</p><h2>Cumplimiento Regulatorio</h2><p>La industria petrolera enfrenta regulaciones ambientales estrictas. La limpieza láser facilita el cumplimiento al eliminar residuos peligrosos.</p>',
    'blog.post9.title': 'Preparación de Soldadura con Limpieza Láser: Guía Técnica',
    'blog.post9.excerpt': 'Por qué los fabricantes líderes están adoptando la limpieza láser para preparación de soldadura y cómo mejora la calidad de las uniones.',
    'blog.post9.content': '<h2>Importancia de la Preparación de Superficie</h2><p>La calidad de una soldadura depende críticamente de la limpieza de la superficie. Óxidos, aceites y contaminantes causan porosidad, fisuras y soldaduras débiles.</p><h2>Ventajas del Láser sobre Métodos Tradicionales</h2><p>El esmerilado deja residuos abrasivos. Los solventes dejan films. La limpieza láser vaporiza todo contaminante sin dejar residuos, creando la superficie ideal.</p><h2>Aplicaciones Específicas</h2><p>Soldadura de acero inoxidable, aluminio, titanio y aleaciones especiales. Cada material requiere parámetros específicos que nuestro sistema ajusta automáticamente.</p><h2>Integración en Líneas de Producción</h2><p>Los sistemas láser pueden integrarse directamente antes de estaciones de soldadura automatizadas, garantizando superficies limpias consistentemente.</p><h2>Reducción de Rechazos</h2><p>Nuestros clientes reportan reducción de hasta 80% en soldaduras rechazadas después de implementar limpieza láser en su proceso.</p>',
    'blog.post10.title': 'Restauración de Monumentos Históricos con Tecnología Láser',
    'blog.post10.excerpt': 'Cómo la limpieza láser preserva el patrimonio cultural al restaurar edificios y monumentos históricos sin daño.',
    'blog.post10.content': '<h2>Preservación del Patrimonio</h2><p>Los monumentos históricos requieren métodos de limpieza que no dañen materiales centenarios. La limpieza láser ofrece la precisión necesaria para esta tarea delicada.</p><h2>Limpieza de Piedra y Mármol</h2><p>El láser elimina siglos de suciedad, hollín y contaminación atmosférica sin afectar la pátina natural ni erosionar detalles escultóricos.</p><h2>Restauración de Metales Ornamentales</h2><p>Bronce, cobre y hierro forjado en edificios históricos se benefician de limpieza láser que revela el acabado original.</p><h2>Documentación y Trazabilidad</h2><p>Cada proyecto de restauración se documenta completamente, cumpliendo con requisitos de conservación de patrimonio cultural.</p><h2>Casos de Éxito</h2><p>Hemos participado en proyectos de restauración de edificios coloniales, monumentos públicos y piezas de museo con resultados excepcionales.</p>',
    
    // Privacy Policy
    'privacy.title': 'Política de Privacidad',
    'privacy.metaDescription': 'Política de privacidad de Marine Laser Clean. Conozca cómo recopilamos, usamos y protegemos su información personal.',
    'privacy.lastUpdated': 'Última actualización',
    'privacy.intro.title': 'Introducción',
    'privacy.intro.content': 'En Marine Laser Clean, respetamos su privacidad y nos comprometemos a proteger sus datos personales. Esta política de privacidad le informará sobre cómo cuidamos sus datos personales cuando visita nuestro sitio web y le informará sobre sus derechos de privacidad.',
    'privacy.dataCollection.title': 'Datos que Recopilamos',
    'privacy.dataCollection.content': 'Podemos recopilar los siguientes tipos de información:',
    'privacy.dataCollection.item1': 'Información de contacto (nombre, correo electrónico, teléfono) cuando nos contacta a través de nuestro formulario',
    'privacy.dataCollection.item2': 'Datos técnicos como dirección IP, tipo de navegador y sistema operativo',
    'privacy.dataCollection.item3': 'Datos de uso sobre cómo utiliza nuestro sitio web',
    'privacy.dataUse.title': 'Cómo Usamos sus Datos',
    'privacy.dataUse.content': 'Utilizamos sus datos personales para los siguientes propósitos:',
    'privacy.dataUse.item1': 'Responder a sus consultas y solicitudes de cotización',
    'privacy.dataUse.item2': 'Mejorar nuestro sitio web y servicios',
    'privacy.dataUse.item3': 'Cumplir con obligaciones legales',
    'privacy.cookies.title': 'Cookies',
    'privacy.cookies.content': 'Nuestro sitio web utiliza cookies para mejorar su experiencia. Para más detalles, consulte nuestra Política de Cookies.',
    'privacy.thirdParty.title': 'Compartir con Terceros',
    'privacy.thirdParty.content': 'No vendemos, comercializamos ni transferimos sus datos personales a terceros. Esto no incluye socios de confianza que nos ayudan a operar nuestro sitio web, siempre que esas partes acuerden mantener esta información confidencial.',
    'privacy.security.title': 'Seguridad de Datos',
    'privacy.security.content': 'Implementamos medidas de seguridad apropiadas para proteger contra acceso no autorizado, alteración, divulgación o destrucción de sus datos personales.',
    'privacy.rights.title': 'Sus Derechos',
    'privacy.rights.content': 'Bajo las leyes de protección de datos aplicables, usted tiene los siguientes derechos:',
    'privacy.rights.item1': 'Derecho de acceso a sus datos personales',
    'privacy.rights.item2': 'Derecho de rectificación de datos inexactos',
    'privacy.rights.item3': 'Derecho de eliminación de sus datos',
    'privacy.rights.item4': 'Derecho de oposición al procesamiento de sus datos',
    'privacy.contact.title': 'Contáctenos',
    'privacy.contact.content': 'Si tiene preguntas sobre esta política de privacidad o desea ejercer sus derechos, contáctenos:',

    // Cookie Policy
    'cookies.title': 'Política de Cookies',
    'cookies.metaDescription': 'Política de cookies de Marine Laser Clean. Conozca cómo utilizamos cookies y tecnologías similares.',
    'cookies.lastUpdated': 'Última actualización',
    'cookies.what.title': '¿Qué son las Cookies?',
    'cookies.what.content': 'Las cookies son pequeños archivos de texto que se almacenan en su dispositivo cuando visita un sitio web. Se utilizan ampliamente para hacer que los sitios web funcionen de manera más eficiente y proporcionar información a los propietarios del sitio.',
    'cookies.types.title': 'Tipos de Cookies que Utilizamos',
    'cookies.types.essential.title': 'Cookies Esenciales',
    'cookies.types.essential.content': 'Estas cookies son necesarias para el funcionamiento básico del sitio web. Incluyen cookies que le permiten recordar sus preferencias de idioma y tema.',
    'cookies.types.analytics.title': 'Cookies de Análisis',
    'cookies.types.analytics.content': 'Estas cookies nos ayudan a entender cómo los visitantes interactúan con nuestro sitio web, recopilando información de forma anónima.',
    'cookies.types.functional.title': 'Cookies Funcionales',
    'cookies.types.functional.content': 'Estas cookies permiten funcionalidades mejoradas y personalización, como recordar su consentimiento de cookies.',
    'cookies.manage.title': 'Cómo Gestionar las Cookies',
    'cookies.manage.content': 'Puede configurar su navegador para rechazar todas las cookies o para indicar cuándo se envía una cookie. Sin embargo, algunas funciones del sitio web pueden no funcionar correctamente sin cookies.',
    'cookies.thirdParty.title': 'Cookies de Terceros',
    'cookies.thirdParty.content': 'Actualmente no utilizamos cookies de terceros para publicidad. Si esto cambia en el futuro, actualizaremos esta política.',
    'cookies.consent.title': 'Su Consentimiento',
    'cookies.consent.content': 'Al usar nuestro sitio web, usted acepta el uso de cookies de acuerdo con esta política. Puede retirar su consentimiento en cualquier momento eliminando las cookies de su navegador.',
    'cookies.contact.title': 'Contáctenos',
    'cookies.contact.content': 'Si tiene preguntas sobre nuestra política de cookies, contáctenos:',

    // Cookie Consent Banner
    'cookieConsent.message': 'Utilizamos cookies para mejorar su experiencia en nuestro sitio web y para entender cómo se utiliza nuestro sitio.',
    'cookieConsent.learnMore': 'Para más información, lea nuestra',
    'cookieConsent.privacyLink': 'Política de Privacidad',
    'cookieConsent.and': 'y',
    'cookieConsent.cookieLink': 'Política de Cookies',
    'cookieConsent.accept': 'Aceptar',
    'cookieConsent.decline': 'Rechazar',
  },
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.about': 'About Us',
    'nav.services': 'Services',
    'nav.gallery': 'Gallery',
    'nav.contact': 'Contact',
    
    // Home
    'home.hero.title': 'Industrial Laser Cleaning',
    'home.hero.subtitle': '6000W laser machine for surface preparation, rust removal, and high-power industrial cleaning',
    'home.hero.cta': 'Request Quote',
    'home.hero.cta2': 'View Services',
    'home.features.title': 'Why Choose Us?',
    'home.features.precision.title': 'Zero Substrate Damage',
    'home.features.precision.desc': 'Laser technology removes only contamination, preserving base metal without abrasion',
    'home.features.eco.title': 'No Secondary Waste',
    'home.features.eco.desc': 'No abrasive media, chemicals, or disposal costs. Only minimal captured dust',
    'home.features.efficient.title': 'Dramatically Faster',
    'home.features.efficient.desc': 'Cleans large areas quickly, reducing client downtime',
    'home.features.versatile.title': 'Laser Precision',
    'home.features.versatile.desc': 'Clean specific areas like weld seams without affecting surrounding material',
    'home.power.title': '6000W Industrial Power',
    'home.power.desc': 'High-power equipment for heavy-duty industrial applications and large-scale projects',
    
    // About
    'about.title': 'About Us',
    'about.subtitle': 'Specialized industrial laser cleaning service providers',
    'about.intro': 'We operate a high-power 6000W rust cleaning laser system, offering industrial-grade surface preparation services for heavy manufacturing, maritime, energy, and aerospace sectors. Our Class 4 equipment handles large-scale projects where client downtime is critical.',
    'about.mission.title': 'Our Technology',
    'about.mission.desc': '6000W laser system for heavy-duty industrial applications. Fast cleaning of large areas with zero substrate damage, no abrasive media, and no chemical waste. Remote operation for hazardous environments.',
    'about.vision.title': 'Business Model',
    'about.vision.desc': 'B2B service provider offering mobile, per-project, and maintenance contracts. We specialize in market education about economic and environmental advantages over traditional methods.',
    'about.values.title': 'Key Advantages',
    'about.values.quality': 'No Waste',
    'about.values.innovation': 'Faster',
    'about.values.commitment': 'Safe',
    'about.values.safety': 'Precise',
    
    // Services
    'services.title': 'Industrial Laser Cleaning Services',
    'services.subtitle': 'B2B solutions for heavy manufacturing, maritime, energy, and more',
    'services.ship.title': 'Maritime & Shipbuilding',
    'services.ship.desc': 'Rust, barnacle, and old paint removal from ship hulls in dry dock. Ballast tank and cargo hold cleaning. Faster and cleaner than traditional sandblasting.',
    'services.machinery.title': 'Manufacturing & Fabrication',
    'services.machinery.desc': 'Pre-treatment for welding steel plates, beams, and pipes. Surface prep for painting on wind turbine towers, ship hulls, and storage tanks. Mold maintenance without abrasive damage.',
    'services.rust.title': 'Energy & Infrastructure',
    'services.rust.desc': 'Cleaning boilers, heat exchangers, and pipelines in power plants. Wind tower maintenance. Bridge restoration without toxic lead paint dust containment.',
    'services.parts.title': 'Aerospace & Automotive',
    'services.parts.desc': 'Refurbishment of turbine blades and engine components where precision is paramount. Classic car chassis and engine block restoration. Zero substrate damage.',
    'services.coating.title': 'Paint Coating',
    'services.coating.desc': 'Complete paint coating services complementary to laser cleaning. Professional application of industrial, anti-corrosive, and epoxy paints for maximum protection after laser preparation.',
    
    // Gallery
    'gallery.title': 'Work Gallery',
    'gallery.subtitle': 'See the quality of our work',
    'gallery.before': 'Before',
    'gallery.after': 'After',
    
    // Contact
    'contact.title': 'Contact Us',
    'contact.subtitle': 'We are here to help you',
    'contact.name': 'Name',
    'contact.email': 'Email',
    'contact.phone': 'Phone',
    'contact.message': 'Message',
    'contact.send': 'Send Message',
    'contact.info.title': 'Contact Information',
    'contact.info.location': 'Cabimas, Zulia, Venezuela',
    'contact.info.phone': '0412-324-3681',
    'contact.info.email': 'lasercleanvz@proton.me',
    
    // Footer
    'footer.rights': 'All rights reserved',
    'footer.location': 'Cabimas, Zulia, Venezuela',
    'footer.company': 'Marine Laser Clean',
    'footer.privacy': 'Privacy Policy',
    'footer.cookies': 'Cookie Policy',
    
    // SEO Meta Tags
    'seo.home.title': 'Marine Laser Clean | Industrial 6000W Laser Cleaning in Venezuela',
    'seo.home.description': 'Professional industrial laser cleaning services with 6000W equipment. Rust removal, weld preparation, maritime cleaning and more. Cabimas, Zulia, Venezuela.',
    'seo.about.title': 'About Us | Marine Laser Clean - Laser Cleaning Experts',
    'seo.about.description': 'Learn about our 6000W laser cleaning technology. Specialized B2B service providers for maritime, manufacturing, energy and aerospace industries.',
    'seo.services.title': 'Industrial Laser Cleaning Services | Marine Laser Clean',
    'seo.services.description': 'Laser cleaning services for maritime, manufacturing, energy and infrastructure. Rust removal, weld preparation, equipment maintenance without substrate damage.',
    'seo.gallery.title': 'Work Gallery | Marine Laser Clean - Before and After',
    'seo.gallery.description': 'See real industrial laser cleaning results. Before and after photos of ship hulls, machinery, pipes and industrial components.',
    'seo.contact.title': 'Contact Us | Marine Laser Clean - Request Quote',
    'seo.contact.description': 'Request a quote for industrial laser cleaning services. Located in Cabimas, Zulia, Venezuela. Personalized attention for your project.',
    
    // Blog
    'nav.blog': 'Blog',
    'blog.title': 'Industrial Laser Cleaning Blog',
    'blog.subtitle': 'News, tips, and insights on laser cleaning technology',
    'blog.metaTitle': 'Industrial Laser Cleaning Blog | Marine Laser Clean',
    'blog.metaDescription': 'Learn about industrial laser cleaning, rust removal, surface preparation, and eco-friendly alternatives to sandblasting for maritime and manufacturing industries.',
    'blog.readMore': 'Read more',
    'blog.category.comparison': 'Comparison',
    'blog.category.maritime': 'Maritime',
    'blog.category.industry': 'Industry',
    'blog.category.environment': 'Environment',
    'blog.category.energy': 'Energy',
    'blog.category.aerospace': 'Aerospace',
    'blog.category.technique': 'Technique',
    'blog.category.oilgas': 'Oil & Gas',
    'blog.category.welding': 'Welding',
    'blog.category.restoration': 'Restoration',
    'blog.post1.title': 'Laser Cleaning vs Sandblasting: Complete Industrial Comparison',
    'blog.post1.excerpt': 'Discover why laser cleaning is replacing traditional sandblasting in maritime and industrial applications. We compare cost, speed, environmental impact, and results.',
    'blog.post2.title': 'Complete Guide to Ship Hull Rust Removal',
    'blog.post2.excerpt': 'Learn best practices for ship hull maintenance using laser technology. Includes before/after, time estimates, and cost benefits.',
    'blog.post3.title': '5 Benefits of Industrial Laser Cleaning in Manufacturing',
    'blog.post3.excerpt': 'How manufacturers save time and money with laser cleaning for weld preparation, mold maintenance, and surface restoration.',
    'blog.post4.title': 'Eco-Friendly Surface Preparation: The Future of Industrial Cleaning',
    'blog.post4.excerpt': 'Explore how laser cleaning eliminates hazardous waste and meets environmental regulations while delivering superior results.',
    'blog.post5.title': 'Wind Turbine Maintenance with Laser Technology',
    'blog.post5.excerpt': 'Case study: How laser cleaning reduces downtime and extends the lifespan of wind turbine components.',
    'blog.post6.title': 'Precision Cleaning for Aerospace Components',
    'blog.post6.excerpt': 'Why aerospace and automotive industries choose laser cleaning for turbine blade and engine block restoration.',
    'blog.cta.title': 'Ready to Transform Your Cleaning Process?',
    'blog.cta.description': 'Contact us for a free consultation and discover how laser cleaning can benefit your operation.',
    'blog.cta.button': 'Request Quote',
    'blog.backToBlog': 'Back to Blog',
    'blog.readTime': 'read',
    'blog.share': 'Share',
    'blog.relatedPosts': 'Related Articles',
    'blog.post1.content': '<h2>What is Laser Cleaning?</h2><p>Laser cleaning uses high-energy light pulses to vaporize contaminants like rust, paint, and oil from metal surfaces. Unlike sandblasting, there are no abrasive media to damage the base substrate.</p><h2>Cost Comparison</h2><p>While laser equipment has a higher initial cost, long-term savings are significant: no consumables, no hazardous waste disposal costs, and lower equipment maintenance.</p><h2>Work Speed</h2><p>With 6000W systems like ours, laser cleaning can be up to 10 times faster than traditional methods in certain applications, dramatically reducing downtime.</p><h2>Environmental Impact</h2><p>Sandblasting generates tons of contaminated waste. Laser cleaning produces only minimal dust that is easily captured, meeting the strictest environmental regulations.</p><h2>Results and Quality</h2><p>Laser cleaning offers consistent and repeatable results, with precise control over cleaning depth, something impossible to achieve with sandblasting.</p>',
    'blog.post2.content': '<h2>Hull Maintenance Challenges</h2><p>Ship hulls face constant corrosion from saltwater, marine fouling, and paint degradation. Regular maintenance is essential for fuel efficiency and structural integrity.</p><h2>Laser Cleaning Process</h2><p>Our 6000W system efficiently removes layers of rust, barnacles, and old paint without damaging the underlying steel. The process is dry, clean, and generates no secondary waste.</p><h2>Dry Dock Advantages</h2><p>Dry dock time is expensive. Laser cleaning significantly reduces surface preparation time, allowing ships to return to service faster.</p><h2>Paint Preparation</h2><p>The resulting surface is ideal for new coating adhesion, with an optimal anchor profile created by the laser process.</p><h2>Success Cases</h2><p>We have successfully treated hulls up to 200 meters in length, with consistent results and satisfied customers throughout the maritime industry.</p>',
    'blog.post3.content': '<h2>Downtime Reduction</h2><p>In manufacturing, every hour of stoppage costs money. Laser cleaning can be performed during short scheduled maintenance, minimizing production interruptions.</p><h2>Superior Weld Preparation</h2><p>A perfectly clean surface is crucial for quality welds. The laser removes oxides, oils, and contaminants without leaving residues that affect welding.</p><h2>Mold Maintenance</h2><p>Injection molds require regular cleaning. Laser cleaning causes no wear like abrasive methods, significantly extending mold life.</p><h2>Consumable Savings</h2><p>No sand, no chemicals, no disposable materials. The only operating costs are electricity and minimal equipment maintenance.</p><h2>Proven ROI</h2><p>Our customers report investment recovery in less than 18 months thanks to elimination of consumables and reduced process time.</p>',
    'blog.post4.content': '<h2>Environmental Regulations</h2><p>Increasingly strict regulations make traditional methods like sandblasting expensive to comply with. Laser cleaning simplifies regulatory compliance.</p><h2>Zero Hazardous Waste</h2><p>Sandblasting with lead paint generates toxic waste expensive to dispose of. Laser cleaning vaporizes contaminants, leaving only easily contained ash.</p><h2>Worker Health</h2><p>No abrasive dust in the air means a safer work environment. Operators only need basic laser eye protection.</p><h2>Carbon Footprint</h2><p>Lower total energy consumption compared to air compressors for sandblasting, and no transport emissions for abrasive media.</p><h2>The Future is Laser</h2><p>Major industries are already migrating to laser technology. Adopting now means being prepared for future regulations.</p>',
    'blog.post5.content': '<h2>Unique Wind Turbine Challenges</h2><p>Wind turbines operate in hostile environments: sea salt, sand, acid rain. Regular maintenance is crucial but difficult due to their height and location.</p><h2>Blade Cleaning</h2><p>Blades accumulate dirt and erosion that reduce aerodynamic efficiency. Laser cleaning restores the surface without damaging the composite material.</p><h2>Towers and Nacelles</h2><p>Tower steel suffers corrosion. Our portable systems can be deployed in the field for on-site maintenance.</p><h2>Maintenance Cost Reduction</h2><p>Compared to scaffolding and sandblasting at height, laser cleaning with mobile systems significantly reduces costs and risks.</p><h2>Lifespan Extension</h2><p>Regular preventive maintenance with laser can extend the lifespan of critical components by years, improving wind farm ROI.</p>',
    'blog.post6.content': '<h2>Aerospace Standards</h2><p>The aerospace industry has the most demanding quality standards. Laser cleaning meets and exceeds these requirements without compromising material integrity.</p><h2>Turbine Blade Refurbishment</h2><p>Aviation turbine blades are extremely expensive. Laser cleaning allows them to be refurbished multiple times without substrate degradation.</p><h2>Engine Components</h2><p>Pistons, cylinder heads, and engine blocks require precise cleaning. The laser removes carbon deposits without affecting critical tolerances.</p><h2>Automotive Restoration</h2><p>Classic and collector vehicles benefit from laser cleaning that reveals original metal without damage, preserving historical value.</p><h2>Traceability and Documentation</h2><p>Our systems can document each process to meet aerospace and automotive traceability requirements.</p>',
    'blog.post7.title': 'Complete Guide to Paint Removal with Laser Technology',
    'blog.post7.excerpt': 'Learn how laser technology revolutionizes industrial paint removal, offering superior results without damaging the base substrate.',
    'blog.post7.content': '<h2>Traditional vs Laser Paint Removal</h2><p>Traditional methods like chemical stripping and sandblasting have significant limitations. Chemicals are toxic and sandblasting damages the substrate. Laser cleaning eliminates these concerns.</p><h2>How It Works</h2><p>The laser rapidly heats the paint layer, vaporizing it instantly. The metal substrate absorbs less energy, remaining intact and ready for new coating.</p><h2>Types of Paint</h2><p>Our 6000W system handles all types of paints: epoxy, polyurethane, anti-corrosive, and even lead paints safely.</p><h2>Industrial Applications</h2><p>Ideal for vehicle fleet renovation, industrial equipment maintenance, metal structure preparation, and machinery restoration.</p><h2>Economic Advantages</h2><p>No chemical waste disposal costs, reduced work time, and surface ready for immediate repainting.</p>',
    'blog.post8.title': 'Laser Cleaning in the Oil and Gas Industry',
    'blog.post8.excerpt': 'Discover how laser cleaning is transforming equipment maintenance in the oil industry with safer and more efficient solutions.',
    'blog.post8.content': '<h2>Oil Industry Challenges</h2><p>Oil equipment faces extreme conditions: H2S corrosion, hydrocarbon buildup, and explosive environments. Traditional cleaning presents significant risks.</p><h2>Safety in ATEX Zones</h2><p>Our laser equipment can be configured for safe operation in classified areas, eliminating spark risks associated with abrasive methods.</p><h2>Pipeline and Valve Cleaning</h2><p>Laser precision allows cleaning of pipe interiors and valve components without extensive disassembly.</p><h2>Platform Maintenance</h2><p>Offshore structures require constant maintenance against marine corrosion. Portable laser cleaning reduces operational downtime.</p><h2>Regulatory Compliance</h2><p>The oil industry faces strict environmental regulations. Laser cleaning facilitates compliance by eliminating hazardous waste.</p>',
    'blog.post9.title': 'Weld Preparation with Laser Cleaning: Technical Guide',
    'blog.post9.excerpt': 'Why leading manufacturers are adopting laser cleaning for weld preparation and how it improves joint quality.',
    'blog.post9.content': '<h2>Importance of Surface Preparation</h2><p>Weld quality critically depends on surface cleanliness. Oxides, oils, and contaminants cause porosity, cracks, and weak welds.</p><h2>Laser Advantages over Traditional Methods</h2><p>Grinding leaves abrasive residues. Solvents leave films. Laser cleaning vaporizes all contaminants without leaving residues, creating the ideal surface.</p><h2>Specific Applications</h2><p>Welding stainless steel, aluminum, titanium, and special alloys. Each material requires specific parameters that our system adjusts automatically.</p><h2>Production Line Integration</h2><p>Laser systems can be integrated directly before automated welding stations, ensuring consistently clean surfaces.</p><h2>Rejection Reduction</h2><p>Our customers report up to 80% reduction in rejected welds after implementing laser cleaning in their process.</p>',
    'blog.post10.title': 'Historical Monument Restoration with Laser Technology',
    'blog.post10.excerpt': 'How laser cleaning preserves cultural heritage by restoring historic buildings and monuments without damage.',
    'blog.post10.content': '<h2>Heritage Preservation</h2><p>Historic monuments require cleaning methods that dont damage centuries-old materials. Laser cleaning offers the precision needed for this delicate task.</p><h2>Stone and Marble Cleaning</h2><p>The laser removes centuries of dirt, soot, and atmospheric pollution without affecting the natural patina or eroding sculptural details.</p><h2>Ornamental Metal Restoration</h2><p>Bronze, copper, and wrought iron in historic buildings benefit from laser cleaning that reveals the original finish.</p><h2>Documentation and Traceability</h2><p>Each restoration project is fully documented, meeting cultural heritage conservation requirements.</p><h2>Success Cases</h2><p>We have participated in restoration projects for colonial buildings, public monuments, and museum pieces with exceptional results.</p>',

    // Privacy Policy
    'privacy.title': 'Privacy Policy',
    'privacy.metaDescription': 'Marine Laser Clean privacy policy. Learn how we collect, use and protect your personal information.',
    'privacy.lastUpdated': 'Last updated',
    'privacy.intro.title': 'Introduction',
    'privacy.intro.content': 'At Marine Laser Clean, we respect your privacy and are committed to protecting your personal data. This privacy policy will inform you about how we care for your personal data when you visit our website and tell you about your privacy rights.',
    'privacy.dataCollection.title': 'Data We Collect',
    'privacy.dataCollection.content': 'We may collect the following types of information:',
    'privacy.dataCollection.item1': 'Contact information (name, email, phone) when you contact us through our form',
    'privacy.dataCollection.item2': 'Technical data such as IP address, browser type and operating system',
    'privacy.dataCollection.item3': 'Usage data about how you use our website',
    'privacy.dataUse.title': 'How We Use Your Data',
    'privacy.dataUse.content': 'We use your personal data for the following purposes:',
    'privacy.dataUse.item1': 'To respond to your inquiries and quote requests',
    'privacy.dataUse.item2': 'To improve our website and services',
    'privacy.dataUse.item3': 'To comply with legal obligations',
    'privacy.cookies.title': 'Cookies',
    'privacy.cookies.content': 'Our website uses cookies to improve your experience. For more details, please see our Cookie Policy.',
    'privacy.thirdParty.title': 'Third Party Sharing',
    'privacy.thirdParty.content': 'We do not sell, trade, or transfer your personal data to third parties. This does not include trusted partners who assist us in operating our website, as long as those parties agree to keep this information confidential.',
    'privacy.security.title': 'Data Security',
    'privacy.security.content': 'We implement appropriate security measures to protect against unauthorized access, alteration, disclosure, or destruction of your personal data.',
    'privacy.rights.title': 'Your Rights',
    'privacy.rights.content': 'Under applicable data protection laws, you have the following rights:',
    'privacy.rights.item1': 'Right to access your personal data',
    'privacy.rights.item2': 'Right to rectification of inaccurate data',
    'privacy.rights.item3': 'Right to erasure of your data',
    'privacy.rights.item4': 'Right to object to processing of your data',
    'privacy.contact.title': 'Contact Us',
    'privacy.contact.content': 'If you have questions about this privacy policy or wish to exercise your rights, contact us:',

    // Cookie Policy
    'cookies.title': 'Cookie Policy',
    'cookies.metaDescription': 'Marine Laser Clean cookie policy. Learn how we use cookies and similar technologies.',
    'cookies.lastUpdated': 'Last updated',
    'cookies.what.title': 'What Are Cookies?',
    'cookies.what.content': 'Cookies are small text files that are stored on your device when you visit a website. They are widely used to make websites work more efficiently and provide information to site owners.',
    'cookies.types.title': 'Types of Cookies We Use',
    'cookies.types.essential.title': 'Essential Cookies',
    'cookies.types.essential.content': 'These cookies are necessary for the basic functioning of the website. They include cookies that allow you to remember your language and theme preferences.',
    'cookies.types.analytics.title': 'Analytics Cookies',
    'cookies.types.analytics.content': 'These cookies help us understand how visitors interact with our website by collecting information anonymously.',
    'cookies.types.functional.title': 'Functional Cookies',
    'cookies.types.functional.content': 'These cookies enable enhanced functionality and personalization, such as remembering your cookie consent.',
    'cookies.manage.title': 'How to Manage Cookies',
    'cookies.manage.content': 'You can set your browser to refuse all cookies or to indicate when a cookie is being sent. However, some website features may not function properly without cookies.',
    'cookies.thirdParty.title': 'Third Party Cookies',
    'cookies.thirdParty.content': 'We currently do not use third-party cookies for advertising. If this changes in the future, we will update this policy.',
    'cookies.consent.title': 'Your Consent',
    'cookies.consent.content': 'By using our website, you consent to the use of cookies in accordance with this policy. You can withdraw your consent at any time by deleting cookies from your browser.',
    'cookies.contact.title': 'Contact Us',
    'cookies.contact.content': 'If you have questions about our cookie policy, contact us:',

    // Cookie Consent Banner
    'cookieConsent.message': 'We use cookies to enhance your experience on our website and to understand how our site is used.',
    'cookieConsent.learnMore': 'For more information, read our',
    'cookieConsent.privacyLink': 'Privacy Policy',
    'cookieConsent.and': 'and',
    'cookieConsent.cookieLink': 'Cookie Policy',
    'cookieConsent.accept': 'Accept',
    'cookieConsent.decline': 'Decline',
  },
  zh: {
    // Navigation
    'nav.home': '首页',
    'nav.about': '关于我们',
    'nav.services': '服务项目',
    'nav.gallery': '作品展示',
    'nav.contact': '联系我们',
    
    // Home
    'home.hero.title': '专业激光清洁',
    'home.hero.subtitle': '为委内瑞拉石油行业提供专业的激光喷砂和清洁服务',
    'home.hero.cta': '索取报价',
    'home.hero.cta2': '查看服务',
    'home.features.title': '为什么选择我们？',
    'home.features.precision.title': '精准',
    'home.features.precision.desc': '最先进的激光技术，效果完美无瑕',
    'home.features.eco.title': '环保',
    'home.features.eco.desc': '无有害化学物质或危险废物',
    'home.features.efficient.title': '高效',
    'home.features.efficient.desc': '显著减少时间和成本',
    'home.features.versatile.title': '多功能',
    'home.features.versatile.desc': '适用于所有类型的表面和材料',
    
    // About
    'about.title': '关于我们',
    'about.subtitle': '拥有多年经验的激光清洁专家',
    'about.intro': '我们是委内瑞拉卡比马斯苏利亚州激光清洁服务的领导者。专注于石油行业，我们提供创新高效的清洁解决方案。',
    'about.mission.title': '我们的使命',
    'about.mission.desc': '提供最高质量的激光清洁服务，确保客户满意和环境保护。',
    'about.vision.title': '我们的愿景',
    'about.vision.desc': '成为委内瑞拉领先的激光清洁服务公司，并将我们的服务扩展到国际。',
    'about.values.title': '我们的价值观',
    'about.values.quality': '质量',
    'about.values.innovation': '创新',
    'about.values.commitment': '承诺',
    'about.values.safety': '安全',
    
    // Services
    'services.title': '我们的服务',
    'services.subtitle': '完整的激光清洁解决方案',
    'services.ship.title': '船舱清洁',
    'services.ship.desc': '为石油行业的驳船和船只提供专业服务。我们清除船舱和金属表面的锈迹、旧漆和污染物。',
    'services.machinery.title': '机械清洁',
    'services.machinery.desc': '工业设备、车辆和重型机械的修复。我们清除腐蚀并为维护准备表面。',
    'services.rust.title': '除锈',
    'services.rust.desc': '有效清除所有类型金属零件上的锈迹。非研磨工艺，保持基材的完整性。',
    'services.parts.title': '零件清洁',
    'services.parts.desc': '为任何尺寸的工业部件提供清洁服务。精确的结果，不会损坏零件。',
    'services.coating.title': '油漆涂层',
    'services.coating.desc': '激光清洁后的完整油漆涂层服务。专业应用工业、防腐和环氧涂料，提供激光处理后的最大保护。',
    
    // Gallery
    'gallery.title': '作品展示',
    'gallery.subtitle': '查看我们的工作质量',
    'gallery.before': '清洁前',
    'gallery.after': '清洁后',
    
    // Contact
    'contact.title': '联系我们',
    'contact.subtitle': '我们随时为您提供帮助',
    'contact.name': '姓名',
    'contact.email': '电子邮件',
    'contact.phone': '电话',
    'contact.message': '留言',
    'contact.send': '发送消息',
    'contact.info.title': '联系信息',
    'contact.info.location': '卡比马斯，苏利亚，委内瑞拉',
    'contact.info.phone': '0412-324-3681',
    'contact.info.email': 'lasercleanvz@proton.me',
    
    // Footer
    'footer.rights': '版权所有',
    'footer.location': '卡比马斯，苏利亚，委内瑞拉',
    'footer.company': 'Marine Laser Clean',
    'footer.privacy': '隐私政策',
    'footer.cookies': 'Cookie政策',
    
    // SEO Meta Tags
    'seo.home.title': 'Marine Laser Clean | 委内瑞拉6000W工业激光清洁',
    'seo.home.description': '专业工业激光清洁服务，配备6000W设备。除锈、焊接准备、海事清洁等。卡比马斯，苏利亚，委内瑞拉。',
    'seo.about.title': '关于我们 | Marine Laser Clean - 激光清洁专家',
    'seo.about.description': '了解我们的6000W激光清洁技术。专业B2B服务提供商，服务于海事、制造、能源和航空航天行业。',
    'seo.services.title': '工业激光清洁服务 | Marine Laser Clean',
    'seo.services.description': '海事、制造、能源和基础设施激光清洁服务。除锈、焊接准备、设备维护，不损坏基材。',
    'seo.gallery.title': '作品展示 | Marine Laser Clean - 清洁前后对比',
    'seo.gallery.description': '查看真实的工业激光清洁效果。船体、机械、管道和工业部件的清洁前后照片。',
    'seo.contact.title': '联系我们 | Marine Laser Clean - 索取报价',
    'seo.contact.description': '索取工业激光清洁服务报价。位于委内瑞拉苏利亚州卡比马斯。为您的项目提供个性化服务。',
    
    // Blog
    'nav.blog': '博客',
    'blog.title': '工业激光清洁博客',
    'blog.subtitle': '激光清洁技术的新闻、技巧和见解',
    'blog.metaTitle': '工业激光清洁博客 | Marine Laser Clean',
    'blog.metaDescription': '了解工业激光清洁、除锈、表面处理以及海事和制造业喷砂的环保替代方案。',
    'blog.readMore': '阅读更多',
    'blog.category.comparison': '比较',
    'blog.category.maritime': '海事',
    'blog.category.industry': '工业',
    'blog.category.environment': '环境',
    'blog.category.energy': '能源',
    'blog.category.aerospace': '航空航天',
    'blog.category.technique': '技术',
    'blog.category.oilgas': '石油天然气',
    'blog.category.welding': '焊接',
    'blog.category.restoration': '修复',
    'blog.post1.title': '激光清洁与喷砂：完整工业比较',
    'blog.post1.excerpt': '了解为什么激光清洁正在取代海事和工业应用中的传统喷砂。我们比较成本、速度、环境影响和结果。',
    'blog.post2.title': '船体除锈完整指南',
    'blog.post2.excerpt': '学习使用激光技术进行船体维护的最佳实践。包括前后对比、时间估算和成本效益。',
    'blog.post3.title': '制造业工业激光清洁的5大优势',
    'blog.post3.excerpt': '制造商如何通过激光清洁节省焊接准备、模具维护和表面修复的时间和金钱。',
    'blog.post4.title': '环保表面处理：工业清洁的未来',
    'blog.post4.excerpt': '探索激光清洁如何消除危险废物并满足环保法规，同时提供卓越的效果。',
    'blog.post5.title': '风力涡轮机激光技术维护',
    'blog.post5.excerpt': '案例研究：激光清洁如何减少停机时间并延长风力涡轮机组件的使用寿命。',
    'blog.post6.title': '航空航天部件精密清洁',
    'blog.post6.excerpt': '为什么航空航天和汽车行业选择激光清洁进行涡轮叶片和发动机缸体修复。',
    'blog.post7.title': '激光技术除漆完整指南',
    'blog.post7.excerpt': '了解激光技术如何革新工业除漆，在不损坏基材的情况下提供卓越效果。',
    'blog.post8.title': '石油天然气行业的激光清洁应用',
    'blog.post8.excerpt': '了解激光清洁如何通过更安全、更高效的解决方案改变石油行业的设备维护。',
    'blog.post9.title': '激光清洁焊接准备：技术指南',
    'blog.post9.excerpt': '为什么领先制造商正在采用激光清洁进行焊接准备，以及它如何提高接头质量。',
    'blog.post10.title': '激光技术修复历史古迹',
    'blog.post10.excerpt': '激光清洁如何在不造成损坏的情况下修复历史建筑和纪念碑，保护文化遗产。',
    'blog.cta.title': '准备好转变您的清洁流程了吗？',
    'blog.cta.description': '联系我们进行免费咨询，了解激光清洁如何使您的运营受益。',
    'blog.cta.button': '索取报价',
    'blog.backToBlog': '返回博客',
    'blog.readTime': '阅读',
    'blog.share': '分享',
    'blog.relatedPosts': '相关文章',
    'blog.post1.content': '<h2>什么是激光清洁？</h2><p>激光清洁使用高能光脉冲从金属表面蒸发锈蚀、油漆和油脂等污染物。与喷砂不同，没有会损坏基材的研磨介质。</p><h2>成本比较</h2><p>虽然激光设备初始成本较高，但长期节省显著：无耗材、无危险废物处理成本、设备维护成本更低。</p><h2>工作速度</h2><p>使用像我们这样的6000W系统，在某些应用中激光清洁可比传统方法快10倍，大大减少停机时间。</p><h2>环境影响</h2><p>喷砂产生大量受污染废物。激光清洁只产生易于捕获的少量粉尘，符合最严格的环保法规。</p><h2>结果和质量</h2><p>激光清洁提供一致且可重复的结果，可精确控制清洁深度，这是喷砂无法实现的。</p>',
    'blog.post2.content': '<h2>船体维护挑战</h2><p>船体面临盐水、海洋污损和油漆降解造成的持续腐蚀。定期维护对燃油效率和结构完整性至关重要。</p><h2>激光清洁工艺</h2><p>我们的6000W系统可有效去除锈层、藤壶和旧漆，而不会损坏底层钢材。该工艺干燥、清洁，不产生二次废物。</p><h2>干坞优势</h2><p>干坞时间昂贵。激光清洁显著减少表面准备时间，使船舶更快恢复服务。</p><h2>涂装准备</h2><p>处理后的表面非常适合新涂层附着，激光工艺创造了最佳的锚固轮廓。</p><h2>成功案例</h2><p>我们已成功处理长达200米的船体，在整个海事行业获得了一致的结果和满意的客户。</p>',
    'blog.post3.content': '<h2>减少停机时间</h2><p>在制造业，每小时停工都意味着损失。激光清洁可在短暂的计划维护期间进行，最大限度减少生产中断。</p><h2>卓越的焊接准备</h2><p>完美清洁的表面对于高质量焊接至关重要。激光可去除氧化物、油脂和污染物，不留下影响焊接的残留物。</p><h2>模具维护</h2><p>注塑模具需要定期清洁。激光清洁不会像研磨方法那样造成磨损，显著延长模具寿命。</p><h2>节省耗材</h2><p>无砂、无化学品、无一次性材料。唯一的运营成本是电力和最低限度的设备维护。</p><h2>经验证的投资回报</h2><p>我们的客户报告，由于消除了耗材并缩短了工艺时间，投资回收期不到18个月。</p>',
    'blog.post4.content': '<h2>环境法规</h2><p>日益严格的法规使喷砂等传统方法的合规成本越来越高。激光清洁简化了法规合规。</p><h2>零危险废物</h2><p>含铅油漆的喷砂会产生昂贵处理的有毒废物。激光清洁蒸发污染物，只留下易于收容的灰烬。</p><h2>工人健康</h2><p>空气中没有研磨粉尘意味着更安全的工作环境。操作员只需基本的激光护目镜保护。</p><h2>碳足迹</h2><p>与喷砂用空压机相比，总能耗更低，且无研磨介质的运输排放。</p><h2>未来是激光</h2><p>主要行业已经在向激光技术迁移。现在采用意味着为未来法规做好准备。</p>',
    'blog.post5.content': '<h2>风力涡轮机的独特挑战</h2><p>风力涡轮机在恶劣环境中运行：海盐、沙子、酸雨。由于高度和位置，定期维护至关重要但困难。</p><h2>叶片清洁</h2><p>叶片积累的污垢和侵蚀会降低空气动力效率。激光清洁可恢复表面而不损坏复合材料。</p><h2>塔架和机舱</h2><p>塔架钢材会腐蚀。我们的便携式系统可在现场部署进行维护。</p><h2>降低维护成本</h2><p>与高空脚手架和喷砂相比，使用移动系统的激光清洁显著降低成本和风险。</p><h2>延长使用寿命</h2><p>使用激光进行定期预防性维护可将关键部件的使用寿命延长数年，提高风电场投资回报。</p>',
    'blog.post6.content': '<h2>航空航天标准</h2><p>航空航天业有最严格的质量标准。激光清洁满足并超越这些要求，同时不影响材料完整性。</p><h2>涡轮叶片翻新</h2><p>航空涡轮叶片极其昂贵。激光清洁允许多次翻新而不会降解基材。</p><h2>发动机部件</h2><p>活塞、气缸盖和发动机缸体需要精确清洁。激光可去除碳沉积而不影响关键公差。</p><h2>汽车修复</h2><p>经典和收藏车辆可从激光清洁中受益，无损显露原始金属，保留历史价值。</p><h2>可追溯性和文档</h2><p>我们的系统可记录每个过程，以满足航空航天和汽车可追溯性要求。</p>',
    'blog.post7.content': '<h2>传统除漆与激光除漆</h2><p>化学剥离和喷砂等传统方法有很大局限性。化学品有毒，喷砂会损坏基材。激光清洁消除了这些担忧。</p><h2>工作原理</h2><p>激光快速加热油漆层，使其瞬间蒸发。金属基材吸收较少的能量，保持完整并准备好进行新涂层。</p><h2>油漆类型</h2><p>我们的6000W系统可处理所有类型的油漆：环氧树脂、聚氨酯、防腐涂料，甚至安全处理含铅油漆。</p><h2>工业应用</h2><p>适用于车队翻新、工业设备维护、金属结构准备和机械修复。</p><h2>经济优势</h2><p>无化学废物处理成本，工作时间减少，表面可立即重新涂装。</p>',
    'blog.post8.content': '<h2>石油行业挑战</h2><p>石油设备面临极端条件：H2S腐蚀、碳氢化合物积聚和爆炸性环境。传统清洁存在重大风险。</p><h2>ATEX区域安全</h2><p>我们的激光设备可配置为在分类区域安全操作，消除与研磨方法相关的火花风险。</p><h2>管道和阀门清洁</h2><p>激光精度允许清洁管道内部和阀门组件，无需大量拆卸。</p><h2>平台维护</h2><p>海上结构需要持续维护以抵抗海洋腐蚀。便携式激光清洁减少运营停机时间。</p><h2>法规合规</h2><p>石油行业面临严格的环境法规。激光清洁通过消除危险废物来促进合规。</p>',
    'blog.post9.content': '<h2>表面准备的重要性</h2><p>焊接质量关键取决于表面清洁度。氧化物、油脂和污染物会导致气孔、裂纹和弱焊缝。</p><h2>激光相对于传统方法的优势</h2><p>研磨会留下研磨残留物。溶剂会留下薄膜。激光清洁蒸发所有污染物而不留残留物，创造理想的表面。</p><h2>具体应用</h2><p>焊接不锈钢、铝、钛和特殊合金。每种材料需要我们系统自动调整的特定参数。</p><h2>生产线集成</h2><p>激光系统可直接集成在自动焊接站之前，确保表面始终清洁。</p><h2>减少废品</h2><p>我们的客户报告，在其流程中实施激光清洁后，焊接废品减少高达80%。</p>',
    'blog.post10.content': '<h2>遗产保护</h2><p>历史古迹需要不会损坏数百年材料的清洁方法。激光清洁为这项精细任务提供所需的精度。</p><h2>石材和大理石清洁</h2><p>激光可去除数百年的污垢、煤烟和大气污染，而不影响自然包浆或侵蚀雕塑细节。</p><h2>装饰金属修复</h2><p>历史建筑中的青铜、铜和锻铁可从激光清洁中受益，显露原始饰面。</p><h2>文档和可追溯性</h2><p>每个修复项目都有完整记录，符合文化遗产保护要求。</p><h2>成功案例</h2><p>我们参与了殖民建筑、公共纪念碑和博物馆藏品的修复项目，取得了卓越成果。</p>',

    // Privacy Policy
    'privacy.title': '隐私政策',
    'privacy.metaDescription': 'Marine Laser Clean隐私政策。了解我们如何收集、使用和保护您的个人信息。',
    'privacy.lastUpdated': '最后更新',
    'privacy.intro.title': '简介',
    'privacy.intro.content': '在Marine Laser Clean，我们尊重您的隐私，并致力于保护您的个人数据。本隐私政策将告知您我们在您访问网站时如何处理您的个人数据，并告知您的隐私权。',
    'privacy.dataCollection.title': '我们收集的数据',
    'privacy.dataCollection.content': '我们可能收集以下类型的信息：',
    'privacy.dataCollection.item1': '通过表单联系我们时的联系信息（姓名、电子邮件、电话）',
    'privacy.dataCollection.item2': 'IP地址、浏览器类型和操作系统等技术数据',
    'privacy.dataCollection.item3': '关于您如何使用我们网站的使用数据',
    'privacy.dataUse.title': '我们如何使用您的数据',
    'privacy.dataUse.content': '我们将您的个人数据用于以下目的：',
    'privacy.dataUse.item1': '回复您的咨询和报价请求',
    'privacy.dataUse.item2': '改进我们的网站和服务',
    'privacy.dataUse.item3': '遵守法律义务',
    'privacy.cookies.title': 'Cookies',
    'privacy.cookies.content': '我们的网站使用cookies来改善您的体验。有关更多详情，请参阅我们的Cookie政策。',
    'privacy.thirdParty.title': '第三方共享',
    'privacy.thirdParty.content': '我们不会向第三方出售、交易或转让您的个人数据。这不包括协助我们运营网站的可信合作伙伴，只要这些方同意对此信息保密。',
    'privacy.security.title': '数据安全',
    'privacy.security.content': '我们实施适当的安全措施，以防止未经授权的访问、更改、披露或销毁您的个人数据。',
    'privacy.rights.title': '您的权利',
    'privacy.rights.content': '根据适用的数据保护法律，您拥有以下权利：',
    'privacy.rights.item1': '访问您个人数据的权利',
    'privacy.rights.item2': '更正不准确数据的权利',
    'privacy.rights.item3': '删除您数据的权利',
    'privacy.rights.item4': '反对处理您数据的权利',
    'privacy.contact.title': '联系我们',
    'privacy.contact.content': '如果您对本隐私政策有疑问或希望行使您的权利，请联系我们：',

    // Cookie Policy
    'cookies.title': 'Cookie政策',
    'cookies.metaDescription': 'Marine Laser Clean Cookie政策。了解我们如何使用cookies和类似技术。',
    'cookies.lastUpdated': '最后更新',
    'cookies.what.title': '什么是Cookies？',
    'cookies.what.content': 'Cookies是访问网站时存储在您设备上的小型文本文件。它们被广泛用于使网站更有效地工作，并向网站所有者提供信息。',
    'cookies.types.title': '我们使用的Cookies类型',
    'cookies.types.essential.title': '必要Cookies',
    'cookies.types.essential.content': '这些cookies对于网站的基本功能是必需的。它们包括允许您记住语言和主题偏好的cookies。',
    'cookies.types.analytics.title': '分析Cookies',
    'cookies.types.analytics.content': '这些cookies帮助我们了解访问者如何与我们的网站互动，通过匿名收集信息。',
    'cookies.types.functional.title': '功能Cookies',
    'cookies.types.functional.content': '这些cookies支持增强的功能和个性化，例如记住您的cookie同意。',
    'cookies.manage.title': '如何管理Cookies',
    'cookies.manage.content': '您可以设置浏览器拒绝所有cookies或在发送cookie时发出提示。但是，没有cookies，某些网站功能可能无法正常工作。',
    'cookies.thirdParty.title': '第三方Cookies',
    'cookies.thirdParty.content': '我们目前不使用第三方广告cookies。如果将来有变化，我们将更新此政策。',
    'cookies.consent.title': '您的同意',
    'cookies.consent.content': '使用我们的网站即表示您同意根据本政策使用cookies。您可以随时通过从浏览器删除cookies来撤回同意。',
    'cookies.contact.title': '联系我们',
    'cookies.contact.content': '如果您对我们的cookie政策有疑问，请联系我们：',

    // Cookie Consent Banner
    'cookieConsent.message': '我们使用cookies来增强您在我们网站上的体验，并了解我们的网站是如何被使用的。',
    'cookieConsent.learnMore': '欲了解更多信息，请阅读我们的',
    'cookieConsent.privacyLink': '隐私政策',
    'cookieConsent.and': '和',
    'cookieConsent.cookieLink': 'Cookie政策',
    'cookieConsent.accept': '接受',
    'cookieConsent.decline': '拒绝',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('es');

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations.es] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
